import {StyleSheet, Platform} from 'react-native';

// Font monospaziato, come i terminali della versione desktop
const MONO = Platform.select({ios: 'Menlo', android: 'monospace', default: 'monospace'});

// Palette HUD
const BG = '#04070d';          // nero profondo
const PANEL = 'rgba(8, 20, 32, 0.85)';
const CYAN = '#00d9ff';
const CYAN_DIM = 'rgba(0, 217, 255, 0.35)';
const TEXT = '#c8f4ff';
const RED = '#ff2d55';
const GREEN = '#00ff9d';
const AMBER = '#ffb300';

// Colori esposti ai componenti per stili calcolati a runtime (es. lo stato
// del radar cambia colore in base a isRecording/isLoading)
export const COLORS = {BG, PANEL, CYAN, CYAN_DIM, TEXT, RED, GREEN, AMBER};

// Diametro del radar centrale e lunghezza del braccio rotante
const RADAR_SIZE = 240;
const RADAR_CENTER = RADAR_SIZE / 2;
const SWEEP_LENGTH = 108;

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: BG,
    },
    scrollContent: {
        flexGrow: 1,
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 24,
    },
    // Riga di intestazione: titolo/sottotitolo a sinistra, orologio a destra
    header: {
        width: '100%',
        maxWidth: 380,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        paddingRight: 56, // lascia spazio al toggle voce, ancorato in alto a destra
        marginBottom: 18,
    },
    headerTitleBlock: {
        flexShrink: 1,
    },
    headerTitle: {
        fontSize: 24,
        fontFamily: MONO,
        fontWeight: 'bold',
        color: CYAN,
        letterSpacing: 3,
        textShadowColor: CYAN,
        textShadowOffset: {width: 0, height: 0},
        textShadowRadius: 14,
    },
    headerSubtitle: {
        fontFamily: MONO,
        fontSize: 9,
        color: CYAN_DIM,
        letterSpacing: 0.5,
        marginTop: 3,
    },
    headerClockBlock: {
        alignItems: 'flex-end',
    },
    headerClockText: {
        fontFamily: MONO,
        fontSize: 16,
        color: TEXT,
        fontWeight: '600',
        letterSpacing: 1,
    },
    headerDateText: {
        fontFamily: MONO,
        fontSize: 9,
        color: CYAN_DIM,
        marginTop: 2,
        letterSpacing: 1,
    },
    // Radar/reattore centrale: cerchi concentrici, braccio rotante, angoli a
    // mirino e nucleo pulsante al centro — sostituisce il vecchio pulsante
    // circolare col microfono.
    radarTouchable: {
        alignItems: 'center',
        marginBottom: 8,
    },
    radarWrapper: {
        width: RADAR_SIZE,
        height: RADAR_SIZE,
        alignItems: 'center',
        justifyContent: 'center',
    },
    radarRingOuter: {
        position: 'absolute',
        width: RADAR_SIZE - 20,
        height: RADAR_SIZE - 20,
        borderRadius: (RADAR_SIZE - 20) / 2,
        borderWidth: 1,
        borderColor: CYAN_DIM,
    },
    radarRingMiddle: {
        position: 'absolute',
        width: RADAR_SIZE - 80,
        height: RADAR_SIZE - 80,
        borderRadius: (RADAR_SIZE - 80) / 2,
        borderWidth: 1,
        borderColor: CYAN_DIM,
    },
    radarRingInner: {
        position: 'absolute',
        width: RADAR_SIZE - 140,
        height: RADAR_SIZE - 140,
        borderRadius: (RADAR_SIZE - 140) / 2,
        borderWidth: 1,
        borderColor: 'rgba(0, 217, 255, 0.5)',
    },
    radarSweep: {
        position: 'absolute',
        width: 2,
        height: SWEEP_LENGTH,
        top: RADAR_CENTER - SWEEP_LENGTH,
        left: RADAR_CENTER - 1,
        backgroundColor: CYAN,
        opacity: 0.85,
        transformOrigin: '50% 100%',
        shadowColor: CYAN,
        shadowOffset: {width: 0, height: 0},
        shadowOpacity: 0.9,
        shadowRadius: 6,
    },
    radarCorner: {
        position: 'absolute',
        width: 22,
        height: 22,
        borderColor: CYAN,
    },
    radarCornerTL: {top: 0, left: 0, borderTopWidth: 2, borderLeftWidth: 2},
    radarCornerTR: {top: 0, right: 0, borderTopWidth: 2, borderRightWidth: 2},
    radarCornerBL: {bottom: 0, left: 0, borderBottomWidth: 2, borderLeftWidth: 2},
    radarCornerBR: {bottom: 0, right: 0, borderBottomWidth: 2, borderRightWidth: 2},
    radarCore: {
        position: 'absolute',
        width: 76,
        height: 76,
        borderRadius: 38,
        backgroundColor: 'rgba(0, 217, 255, 0.08)',
        borderWidth: 1,
        borderColor: CYAN,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: CYAN,
        shadowOffset: {width: 0, height: 0},
        shadowOpacity: 0.9,
        shadowRadius: 16,
        elevation: 10,
    },
    radarCoreText: {
        color: CYAN,
        fontFamily: MONO,
        fontSize: 11,
        fontWeight: 'bold',
        letterSpacing: 1,
        textAlign: 'center',
    },
    statusRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 12,
    },
    statusDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        marginRight: 8,
    },
    statusText: {
        fontFamily: MONO,
        fontSize: 12,
        letterSpacing: 2,
        fontWeight: '600',
    },
    // Activity log: cronologia scorrevole degli scambi, come nella versione
    // desktop Mark-LII
    activityLogContainer: {
        width: '100%',
        maxWidth: 380,
        height: 92,
        backgroundColor: PANEL,
        borderWidth: 1,
        borderColor: CYAN_DIM,
        borderRadius: 4,
        padding: 10,
        marginTop: 16,
        marginBottom: 16,
    },
    activityLogTitle: {
        fontFamily: MONO,
        fontSize: 10,
        color: CYAN_DIM,
        letterSpacing: 2,
        marginBottom: 4,
    },
    activityLogScroll: {
        flex: 1,
    },
    activityLogLine: {
        fontFamily: MONO,
        fontSize: 11,
        color: TEXT,
        lineHeight: 16,
        marginBottom: 3,
    },
    activityLogLabelUser: {
        color: GREEN,
        fontWeight: 'bold',
    },
    activityLogLabelJarvis: {
        color: CYAN,
        fontWeight: 'bold',
    },
    activityLogEmpty: {
        fontFamily: MONO,
        fontSize: 11,
        color: CYAN_DIM,
        fontStyle: 'italic',
    },
    thirdCon: {
        width: '100%',
        maxWidth: 380,
        height: 220,
        backgroundColor: PANEL,
        borderWidth: 1,
        borderColor: CYAN_DIM,
        borderRadius: 4,
        marginBottom: 20,
        padding: 20,
        shadowColor: CYAN,
        shadowOffset: {width: 0, height: 0},
        shadowOpacity: 0.4,
        shadowRadius: 16,
        elevation: 8,
    },
    responseScrollView: {
        flex: 1,
        width: '100%',
    },
    responseScrollViewContent: {
        flexGrow: 1,
        justifyContent: 'center',
    },
    resp: {
        color: TEXT,
        fontFamily: MONO,
        fontSize: 15,
        letterSpacing: 0.5,
        textAlign: 'center',
        lineHeight: 26,
        textShadowColor: CYAN_DIM,
        textShadowOffset: {width: 0, height: 0},
        textShadowRadius: 8,
    },
    // Contenitore dei controlli sotto la risposta: microfono, input testuale,
    // scelta voce, cancella chat, ferma
    controlsContainer: {
        width: '100%',
        maxWidth: 380,
        alignItems: 'center',
    },
    // Pulsante toggle voce, ancorato in alto a destra sopra tutto il resto
    voiceToggleButton: {
        position: 'absolute',
        top: 16,
        right: 16,
        zIndex: 10,
        width: 44,
        height: 44,
        borderRadius: 22,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(0, 217, 255, 0.08)',
        borderWidth: 1,
        borderColor: CYAN,
        shadowColor: CYAN,
        shadowOffset: {width: 0, height: 0},
        shadowOpacity: 0.6,
        shadowRadius: 10,
    },
    voiceToggleButtonText: {
        fontSize: 20,
    },
    // Riga con campo di testo + pulsante invio, per scrivere comandi senza voce
    textInputRow: {
        flexDirection: 'row',
        alignItems: 'center',
        width: '100%',
        maxWidth: 380,
        marginTop: 18,
    },
    textInput: {
        flex: 1,
        color: TEXT,
        fontFamily: MONO,
        fontSize: 14,
        paddingVertical: 10,
        paddingHorizontal: 14,
        backgroundColor: PANEL,
        borderWidth: 1,
        borderColor: CYAN_DIM,
        borderRadius: 3,
    },
    sendButton: {
        marginLeft: 8,
        width: 42,
        height: 42,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(0, 217, 255, 0.08)',
        borderWidth: 1,
        borderColor: CYAN,
        borderRadius: 3,
        shadowColor: CYAN,
        shadowOffset: {width: 0, height: 0},
        shadowOpacity: 0.6,
        shadowRadius: 8,
    },
    sendButtonText: {
        color: CYAN,
        fontSize: 18,
        fontWeight: 'bold',
    },
    selectVoiceButton: {
        marginTop: 25,
        paddingVertical: 12,
        paddingHorizontal: 24,
        backgroundColor: 'rgba(0, 217, 255, 0.08)',
        borderWidth: 1,
        borderColor: CYAN,
        borderRadius: 3,
        shadowColor: CYAN,
        shadowOffset: {width: 0, height: 0},
        shadowOpacity: 0.6,
        shadowRadius: 10,
    },
    selectVoiceButtonText: {
        color: CYAN,
        fontFamily: MONO,
        fontSize: 14,
        fontWeight: 'bold',
        letterSpacing: 2,
        textAlign: 'center',
    },
    clearChatButton: {
        marginTop: 14,
        paddingVertical: 11,
        paddingHorizontal: 20,
        backgroundColor: 'rgba(255, 45, 85, 0.08)',
        borderWidth: 1,
        borderColor: RED,
        borderRadius: 3,
        shadowColor: RED,
        shadowOffset: {width: 0, height: 0},
        shadowOpacity: 0.5,
        shadowRadius: 8,
    },
    clearChatButtonText: {
        color: RED,
        fontFamily: MONO,
        fontSize: 13,
        fontWeight: 'bold',
        letterSpacing: 2,
        textAlign: 'center',
    },
    modalOverlay: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(4, 7, 13, 0.96)',
    },
    modalContent: {
        backgroundColor: PANEL,
        borderWidth: 1,
        borderColor: CYAN,
        borderRadius: 4,
        padding: 24,
        width: '90%',
        maxHeight: '80%',
        shadowColor: CYAN,
        shadowOffset: {width: 0, height: 0},
        shadowOpacity: 0.7,
        shadowRadius: 20,
        elevation: 15,
    },
    modalTitle: {
        fontSize: 17,
        fontFamily: MONO,
        fontWeight: 'bold',
        color: CYAN,
        letterSpacing: 2.5,
        marginBottom: 20,
        textAlign: 'center',
        textShadowColor: CYAN,
        textShadowOffset: {width: 0, height: 0},
        textShadowRadius: 10,
    },
    voiceList: {
        maxHeight: 300,
        marginBottom: 10,
    },
    voiceItem: {
        padding: 14,
        marginBottom: 8,
        borderRadius: 3,
        backgroundColor: 'rgba(0, 217, 255, 0.04)',
        borderColor: CYAN_DIM,
        borderWidth: 1,
    },
    selectedVoiceItem: {
        borderColor: CYAN,
        borderWidth: 1,
        backgroundColor: 'rgba(0, 217, 255, 0.15)',
    },
    voiceText: {
        color: TEXT,
        fontFamily: MONO,
        fontSize: 13,
        letterSpacing: 0.5,
    },
    noVoicesText: {
        color: CYAN_DIM,
        fontFamily: MONO,
        fontSize: 13,
        letterSpacing: 1,
        textAlign: 'center',
        marginTop: 20,
    },
    closeModalButton: {
        marginTop: 20,
        paddingVertical: 13,
        backgroundColor: 'rgba(255, 45, 85, 0.1)',
        borderWidth: 1,
        borderColor: RED,
        borderRadius: 3,
        alignItems: 'center',
    },
    closeModalButtonText: {
        color: RED,
        fontFamily: MONO,
        fontSize: 14,
        fontWeight: 'bold',
        letterSpacing: 2,
    },
    stopCon: {
        marginTop: 14,
        paddingVertical: 11,
        paddingHorizontal: 50,
        backgroundColor: 'rgba(255, 45, 85, 0.08)',
        borderWidth: 1,
        borderColor: RED,
        borderRadius: 3,
        alignItems: 'center',
    },
    stop: {
        color: RED,
        fontFamily: MONO,
        fontSize: 13,
        fontWeight: 'bold',
        letterSpacing: 2,
    },
    deniedContainer: {
        flex: 1,
        backgroundColor: BG,
        alignItems: 'center',
        justifyContent: 'center',
    },
    blurBox: {
        width: 250,
        paddingVertical: 40,
        alignItems: 'center',
        borderRadius: 4,
        borderColor: RED,
        borderWidth: 1,
        backgroundColor: 'rgba(255, 45, 85, 0.05)',
        shadowColor: RED,
        shadowOffset: {width: 0, height: 0},
        shadowOpacity: 0.6,
        shadowRadius: 16,
    },
    lockIcon: {
        fontSize: 60,
        marginBottom: 10,
        color: RED,
    },
    deniedText: {
        fontSize: 20,
        fontFamily: MONO,
        color: TEXT,
        fontWeight: 'bold',
        letterSpacing: 3,
        marginBottom: 5,
    },
    subText: {
        fontSize: 13,
        fontFamily: MONO,
        color: RED,
        letterSpacing: 1.5,
        opacity: 0.85,
    },
});
